# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('case_title', models.CharField(max_length=200)),
                ('test_preconditions', models.CharField(max_length=200)),
                ('repro_steps', models.CharField(max_length=200)),
                ('extra_notes', models.CharField(max_length=200)),
            ],
        ),
    ]
