# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('repro_steps', models.TextField()),
            ],
        ),
    ]
