# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0002_user_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_story',
            old_name='description',
            new_name='case_title',
        ),
        migrations.RenameField(
            model_name='user_story',
            old_name='title',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='user_story',
            old_name='repro_steps',
            new_name='test_preconditions',
        ),
    ]
